# Generated by Django 5.2.5 on 2025-09-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetails',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
